### ISSUE TITLE
return of deleted files on ubuntu20 amd64 

### ISSUE THREAD

**Issue by dkorenci** [internxt/drive-desktop#107]
Hi, I've been using the drive on Linux desktop for some time now, and at least 
for versions 1.8.0 and 1.9.0 (latest) drive automatically restores deleted files from the cloud!
At first, I could not believe it so I tested this "feature" and it really exists.
I thought that it restores the deleted files from another synced computer (which would also be a bug), 
but no, it restores them when only one computer is online.

This reduces the usability quite a lot, for example if one handles a lot of documents and 
moves them around, the moved document return from the dead, leading to clutter and an increase in used space.

I find it hard to believe there are priced plans for software on this level of completeness,
unless of course, the bug disappears in the paid version.

**Comment by hriva** [comment]
Hi, this happens to me too. My internxt syncs with a folder in my PC, but sometimes other programs must read files from those folders and erase them. The drive app redownloads the erased files and this causes errors and duplicates. Specially when handling documents.

This also happens if I rename a file or a folder. The drive seems to asume it is not downloaded and not only redownloads the renamed file, it uploads the new file too.

Love the app, it is just a little hard to use it for a highly dynamic back up system

**Comment by AlexMenor** [comment]
Hi @dkorenci and @hriva. This is happening because both directories are not completely in sync and we can't know if the file you deleted is a deleted file or if its been just added to the other directory, so we take the safe approach and just have it in both. When both directories are in sync we can safely delete that file though.

Please, check if you have some issue when clicking in the gear in the top right of the widget.

**Comment by dkorenci** [comment]
Hi @AlexMenor, thank you for the reply. I do not understand, is the issue that two (or more) devices sharing the same 
Internxt folder/account are not in sync? For me, this does not seem to be the case. Or are you talking about two directories
within the same Internxt folder/account?

**Comment by AlexMenor** [comment]
Hi @dkorenci, not quite. The thing is that your local internxt folder and your internxt account have to be in sync (that is, containing the same folders and files) before we can make smarter decisions about deletes in either your internxt account or your local internxt folder. It has to do with our current sync algorithm, but we'll probably improve it soon so it doesn't need that sync status.

**Comment by dkorenci** [comment]
The folders are in sync file-wise 99.9%, definitely the sub-folder in which the (un)deleted files reside.
Only thing that I see that could break the sync is various apps constantly writing in the working folders in the background. 
Is this the case?
If it is, for me this means that I am almost never in sync and I will never be able to delete files, 
which really dowgrades the usability drastically....

**Comment by AlexMenor** [comment]
Nope, that's not the case. That workflow is totally supported. Please, contact support and point them to this issue. They'll ask you to send your logs so I can see what's happening.

**Comment by dkorenci** [comment]
Ok, will do, thank you

**Comment by AlexMenor** [comment]
Hi everyone, this should be fixed in yesterday's release
