### ISSUE TITLE
Syncing Issue since 1.4.0

### ISSUE THREAD

**Issue by Desibabe** [internxt/drive-desktop#91]
I just upgraded to 1.8.0 and thinking that the syncing issue will go away in 1.5, 1.6, 1.7, 1.8. I want upload essential files to the cloud. I even emailed to help@internxt.com no avail. The cloud based app isn't working for me, Please share your experience.   

! [image](https://user-images.githubusercontent.com/65683417/158066291-359d6b5c-52f8-46f0-901e-c51947582320.png)

**Comment by hschoond** [comment]
directly after upgrading from version 1.7.1 to 1.8.0 i got this message on my pc:

We could not get the status of your current files, we'll try again later

What can i do?

**Comment by Desibabe** [comment]
Good news! Reply received from Sasha:

**Hi there,
﻿We are really sorry that you have this kind of problem with our service, but I will try to help you to fix it.
﻿
﻿We have detected this error some days before and we have already fixed it, but unfortunately, you will be able to fix it on your PC only with a new upgrade. So in a few days, we are going to launch a new version of our Desktop app with fixed bugs and also with more new features.
﻿
﻿We will notify you when it will be launched and we are sorry for the inconvenience!**

**Comment by Desibabe** [comment]
**I believe there is going to be a huge update 1.9 wait for the new release.**

**Comment by devhawkio** [comment]
@Desibabe We are still waiting for 1.9 right? This drive app in unusable and the dev team is non existent here, which is very disappointing.

**Comment by RasheedAZ** [comment]
Fixed now in 1.90?

**Comment by sg-gs** [comment]
Hey guys, we are checking all the repository issues in order to get all the feedback from our users, sorry to read these things. We were smaller and definitely not had enough resources to fix all the issues as a startup is commonly a place where there are fires everywhere, every day.

Please, if any of you, free or subscribed are facing any sync issues, please write to hello@internxt.com, and our internal support system will create a support ticket or better, report the issue via the reporting tool that is integrated into the Desktop App. 

We are starting to change a lot of things here and one of the main things is providing better support to our beloved Desktop users community. 

@Desibabe @RasheedAZ @devhawkio @hschoond
